WisePriceClient/Models/Deal.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WisePriceClient.Models
{
  public class Deal
  {
    public int DealId { get; set; }
    public int ItemId { get; set; }
    public int LocationId { get; set; }
    public string UserId { get; set; }
    public string Price { get; set; }
    public DateTime TimeUpdated { get; set; }
    public int UpVotes { get; set; }
    public int DownVotes { get; set; }
    public virtual Item Item { get; set; }
    public virtual Location Location { get; set; }

    public Deal() { }

    public Deal(int itemId, int locationId, string price, string userId)
    {
      ItemId = itemId;
      LocationId = locationId;
      Price = price;
      UserId = userId;
    }

    public Deal(int dealId, int itemId, int locationId, string price, string userId)
    {
      DealId = dealId;
      ItemId = itemId;
      LocationId = locationId;
      Price = price;
      UserId = userId;
    }

    public static List<Deal> GetAll()
    {
      var apiCallTask = ApiHelper.GetAllDeals();
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<Deal> dealList = JsonConvert.DeserializeObject<List<Deal>>(jsonResponse.ToString());

      return dealList;
    }

    // Gets Count of all deals
    public static int GetCount()
    {
      var apiCallTask = ApiHelper.GetDealCount();
      var result = int.Parse(apiCallTask.Result);
      return result;
    }

    public static Deal Get(int id)
    {
      var apiCallTask = ApiHelper.GetDeal(id);
      var result = apiCallTask.Result;
      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      Deal deal = JsonConvert.DeserializeObject<Deal>(jsonResponse.ToString());
      return deal;
    }

    public static void Post(Deal newDeal)
    {
      string jsonReview = JsonConvert.SerializeObject(newDeal);
      var apiCallTask = ApiHelper.PostDeal(jsonReview);
    }

    public static void Put(Deal dealToEdit)
    {
      string jsonReview = JsonConvert.SerializeObject(dealToEdit);
      var apiCallTask = ApiHelper.PutDeal(dealToEdit.DealId, jsonReview);
    }

    public static void Delete(int id)
    {
      var apiCallTask = ApiHelper.DeleteDeal(id);
    }
  }
}

WisePriceClient/Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WisePriceClient.Models;

namespace WisePriceClient.Controllers
{
  public class DealsController : Controller
  {
    // Don't remove the "= 1", this sets the default page to 1
    public IActionResult Index(int id = 1)
    {
      string page = $"{id}";
      ViewBag.Page = id;
      ViewBag.Size = 20;
      ViewBag.DealCount = Deal.GetCount();

      var allDeals = Deal.GetAll();
      return View(allDeals);
    }

    public IActionResult Create()
    {
      ViewBag.allItems = Item.GetAll().OrderBy(item => item.ItemName).ToList();
      ViewBag.allLocations = Location.GetAll().OrderBy(location => location.Name).ToList();
      ViewBag.userId = User.Identity.GetUserId();

      return View();
    }

    [HttpPost]
    public IActionResult Create(string ItemId, string newItemName, string LocationId, string Price, string UserId)
    {
      // // Make sure user is logged in
      if (UserId != null)
      {
        // Create new item and set ItemId = to newItem's Id
        if (newItemName != null)
        {
          Item newItem = new Item(newItemName);
          Item.Post(newItem);
          List<Item> allItems = Item.GetAll();
          foreach (Item item in allItems)
          {
            if (item.ItemName == newItemName)
            {
              ItemId = item.ItemId.ToString();
            }
          }
        }

        int ItemIdInt = int.Parse(ItemId);
        int LocationIdInt = int.Parse(LocationId);

        Deal newDeal = new Deal(ItemIdInt, LocationIdInt, Price, UserId);
        Deal.Post(newDeal);
        return RedirectToAction("Index");
      }
      else
      {
        return RedirectToAction("Index");
      }
    }

    [HttpPost]
    public IActionResult Index(Deal newDeal)
    {
      ViewBag.ItemId = Item.GetAll(); // returns a list of Item objects for dropdown of items
      Deal.Post(newDeal);
      return RedirectToAction("Index");
    }

    public IActionResult Edit(int id)
    {
      ViewBag.allItems = Item.GetAll().OrderBy(item => item.ItemName).ToList();
      ViewBag.allLocations = Location.GetAll().OrderBy(location => location.Name).ToList();
      ViewBag.userId = User.Identity.GetUserId();
      var selectedDeal = Deal.Get(id);
      return View(selectedDeal);
    }

    [HttpPost]
    public IActionResult Edit(string ItemId, string newItemName, string LocationId, string Price, string UserId, int DealId)
    {
      // // Make sure user is logged in
      if (User.Identity.IsAuthenticated)
      //if (UserId != null)
      {
        // Create new item and set ItemId = to newItem's Id
        if (newItemName != null)
        {
          Item newItem = new Item(newItemName);
          Item.Post(newItem);
          List<Item> allItems = Item.GetAll();
          foreach (Item item in allItems)
          {
            if (item.ItemName == newItemName)
            {
              ItemId = item.ItemId.ToString();
            }
          }
        }

        int ItemIdInt = int.Parse(ItemId);
        int LocationIdInt = int.Parse(LocationId);

        Deal dealToEdit = new Deal(DealId, ItemIdInt, LocationIdInt, Price, UserId);
        Deal.Put(dealToEdit);
        return RedirectToAction("Posted");
      }
      else
      {
        return RedirectToAction("Posted");
      }
    }

    [HttpPost]
    public IActionResult Details(int id, Deal dealToEdit)
    {
      dealToEdit.DealId = id;
      Deal.Put(dealToEdit);
      return RedirectToAction("Details", id);
    }

    [HttpPost]
    public IActionResult Delete(int DealId)
    {
      Deal.Delete(DealId);
      return RedirectToAction("Posted");
    }

    public IActionResult Pinned(int id = 1)
    {
      try
      {
        string page = $"{id}";
        ViewBag.Page = id;
        ViewBag.Size = 20;
        string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ViewBag.DealCount = PinnedDeal.GetCount(userId);
        var allPinnedDeals = PinnedDeal.GetAll(userId);
        return View(allPinnedDeals);
      }
      catch (Exception ex)
      {
        TempData["ErrorMessage"] = "You are not logged in. Please log in to see your pinned deals.";
        Console.WriteLine("Exception Error in Deals Controller Pinned Route: " + ex);
        return View();
      }
    }

    // Don't remove the "= 1", this sets the default page to 1
    public IActionResult Posted(int id = 1)
    {
      try
      {
        string page = $"{id}";
        ViewBag.Page = id;
        ViewBag.Size = 20;
        string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ViewBag.DealCount = PostedDeal.GetCount(userId);

        var allPostedDeals = PostedDeal.GetAll(userId);
        return View(allPostedDeals);
      }
      catch (Exception ex)
      {
        TempData["ErrorMessage"] = "You are not logged in. Please log in to see your posted deals.";
        Console.WriteLine("Exception Error in Deals Controller Posted Route: " + ex);
        return View();
      }
    }
  }
}

WisePriceClient/Controllers/PinnedDealsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Mvc;
using WisePriceClient.Models;

namespace WisePriceClient.Controllers
{
  public class PinnedDealsController : Controller
  {
    // public IActionResult Index(int id = 1)
    // {
    //   string page = $"{id}";
    //   ViewBag.Page = id;
    //   ViewBag.Size = 20;
    //   string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    //   ViewBag.DealCount = PinnedDeal.GetCount(userId);

    //   var allPinnedDeals = PinnedDeal.GetAll(userId);
    //   return View(allPinnedDeals);
    // }

    [HttpPost]
    public IActionResult PinnedPost(int dealId)
    {
      string userId = User.Identity.GetUserId();
      APIUser user = APIUser.Get(userId);
      PinnedDeal newPinnedDeal = new PinnedDeal(userId, dealId, user);
      PinnedDeal.Post(newPinnedDeal);
      return RedirectToAction("Index", "Deals");
    }
  }
}

WisePriceClient/Views/Deals/Create.cshtml
@{
  ViewData["Title"] = "Add Deal";
}

@model Deal

<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous">
</script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#item-field').hide();
    $('#item-btn').click(function() {
      $('#item-field').toggle();
      $("#item-input").val('');
    });
    $('.ui.dropdown').dropdown();
  });
</script>

<div class='create-body'>

  <div class='create-top'>
      <div class='col'></div>
      <h1>Add A Deal</h1>
      <div class='col'></div>
  </div>

  <div class='create-sub'>

    <form asp-controller='Deals' asp-action='Create' method='post' class="ui equal width form">
      <div class="field">
        <label for='Item'>Item</label>
        <div class="ui search selection dropdown">
          <input type="hidden" id='Item' asp-for='ItemId'>
          <i class="dropdown icon"></i>
          <div class="default text">Select the item</div>
          <div class="menu">
            @foreach (Item item in ViewBag.allItems)
            {
              <div data-value='@item.ItemId' class="item">
                @item.ItemName
              </div>
            }
          </div>
        </div>
      </div>

      <div class='item-btn-container field'>
        <a id="item-btn" type='button'>I don't see my item</a>
      </div>

      <div id='item-field' class="field">
        <label for='item-input'>Add a new item</label>
        <input id='item-input' name='newItemName' type="text" placeholder="Spaghetti Squash">
      </div>

      <div class="field">
        <label for='Location'>Location</label>
        <div class="ui search selection dropdown">
          <input type="hidden" asp-for='LocationId'>
          <i class="dropdown icon"></i>
          <div class="default text">Select the location</div>
          <div class="menu">
              @foreach (Location location in ViewBag.allLocations)
              {
                <div data-value='@location.LocationId' class="item"><strong>@location.Name</strong> @location.Address</div>
              }
          </div>
        </div>
      </div>

      <div class="field">
        <label for='Price'>Price and unit amount</label>
        <input type="text" id='Price' asp-for='Price' placeholder="$3.50 per lb" required>
      </div>

      <input type="hidden" asp-for="UserId" value="@ViewBag.userId"/>
      
      <div class='submit-field'>
        <button class='ui button' type='submit'>Add Deal</button>
        <small><a asp-action='Index'>Cancel</a></small>
      </div>
    </form>
  </div>
</div>

WisePriceClient/Views/Deals/Edit.cshtml
@{
    ViewData["Title"] = "Edit Deal";
}

@model Deal

<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous">
</script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#item-field').hide();

    $('#item-btn').click(function() {
      $('#item-field').toggle();
      $("#item-input").val('');
    });

    $('.ui.dropdown')
      .dropdown()
    ;
  });
</script>

<div class='create-body'>
  <div class='create-top'>
      <div class='col'></div>
      <h1>Edit Deal</h1>
      <div class='col'></div>
  </div>
  <h4>@Model.Item.ItemName: @Model.Price, at @Model.Location.Name @Model.Location.Address</h4>


  <div class='create-sub'>

    <form asp-controller='Deals' asp-action='Edit' method='post' class="ui equal width form">

      <div class="field">
        <label for='Item'>Item</label>
        <div class="ui search selection dropdown">
          <input type="hidden" id="Item" asp-for='ItemId'>
          <i class="dropdown icon"></i>
          <div class="default text">@Model.Item.ItemName</div>
          <div class="menu">
            @foreach (Item item in ViewBag.allItems)
            {
              <div data-value='@item.ItemId' class="item">@item.ItemName</div>
            }
          </div>
        </div>
      </div>

      <div class='item-btn-container field'>
        <a id="item-btn" type='button'>I don't see my item</a>
      </div>

      <div id='item-field' class="field">
        <label for='Item'>Add a new item</label>
        <input id='item-input' type="text" placeholder="Spaghetti Squash">
      </div>
        
      <div class="field">
        <label for='Location'>Location</label>
        <div class="ui search selection dropdown">
          <input type="hidden" id="Location" asp-for='LocationId'>
          <i class="dropdown icon"></i>
          <div class="default text"><strong>@Model.Location.Name</strong> @Model.Location.Address</div>
          <div class="menu">
            @foreach (Location location in ViewBag.allLocations)
            {
              <div data-value='@location.LocationId' class="item"><strong>@location.Name</strong> @location.Address</div>
            }
          </div>
        </div>
      </div>

      <div class="field">
        <label for='Price'>Price per unit</label>
        <input type="text" id='Price' asp-for='Price' placeholder="@Model.Price" required>
      </div>

      <input type="hidden" asp-for="UserId" value="@ViewBag.userId"/>

      <input type="hidden" asp-for="DealId" value="@Model.DealId"/>

      <div class='submit-field'>
        <button class='ui button' type='submit'>Edit Deal</button>
        <small><a asp-action='Index'>Cancel</a></small>
      </div>

    </form>
  </div>

</div>

WisePriceClient/Views/Deals/Index.cshtml
@{
    ViewData["Title"] = "Deals";
}

@{
  int nextPage = ViewBag.Page + 1;
  int prevPage = ViewBag.Page - 1;
}

@using WisePriceClient.Models
@model List<Deal>

<div class='deals-body'>
  <div class='deals-top'>
    <div class='col'></div>
    <h1>Deals</h1>
    <div class='col'>
      <div class='pagination'>
        <div>
          @((ViewBag.Page - 1) * (ViewBag.Size) + 1) to @((ViewBag.Page - 1) * (ViewBag.Size) + Model.Count) of @ViewBag.DealCount results
        </div>
        <div>
          <div class='page-nav'>
            @if (ViewBag.Page > 1)
            {
              <a  asp-action="Index" asp-route-id="@(prevPage)"> &lt Previous </a>
            }

            <span class="current-page">Page @ViewBag.Page</span>
            
            @if (ViewBag.Page <= ViewBag.DealCount/ViewBag.Size)
            {
              <a asp-action="Index" asp-route-id="@(nextPage)">Next &gt </a>
            }
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="ui search">
    <div class="ui icon input">
      <input class="prompt" type="text" placeholder="Search by item...">
      <i class="search icon"></i>
    </div>
  </div>

  <div class='deals-cards-container'>
    @foreach (var deal in Model)
    {
      <div class="ui cards">
        <div class="card">
          <div class="ui top">
            <form asp-controller="PinnedDeals" asp-action="PinnedPost" method="post">
              <input type='hidden' value='@deal.DealId' name='DealId'>
              <button type="submit" id='invis-btn'><i class='thumbtack icon large'></i></button>
            </form>
          </div>
          <div class="content">
            <div class="header">
              @deal.Item.ItemName
              <h4>
                @deal.Price
              </h4>
            </div>
            <div class="description">
              <div>
                @deal.Location.Name
              </div>
              <div>
                @deal.Location.Address
              </div>
              <div>
                @deal.TimeUpdated
              </div>
              @* <div>
                @deal.UserId
              </div> *@
            </div>
          </div>
          <div class="ui bottom">
            <a><i class="thumbs up outline icon blue large"></i></a>
            <a><i class="thumbs down outline icon red large"></i></a>
          </div>
        </div>
      </div>
    }
  </div>
</div>

WisePriceClient/Views/Deals/Pinned.cshtml
@{
    ViewData["Title"] = "My Pinned Deals";
}

@{
  int nextPage = ViewBag.Page + 1;
  int prevPage = ViewBag.Page - 1;
}

@using WisePriceClient.Models
@model List<PinnedDeal>

<div class="exceptionError">
@if (TempData.ContainsKey("ErrorMessage"))
{
  <div class='deals-body'>
    <div class='deals-top'>
      <div class='col'></div>
      <h1>My Pinned Deals</h1>
      <div class='col'>
      </div>
    </div>
    <h4>@TempData["ErrorMessage"]</h4>
  </div>
}
else
{


  <div class='deals-body'>
    <div class='deals-top'>
      <div class='col'></div>
      <h1>My Pinned Deals</h1>
      <div class='col'>
        <div class='pagination'>
          <div>
            @((ViewBag.Page - 1) * (ViewBag.Size) + 1) to @((ViewBag.Page - 1) * (ViewBag.Size) + Model.Count) of @ViewBag.DealCount results
          </div>
          <div>
            <div class='page-nav'>
              @if (ViewBag.Page > 1)
              {
                <a  asp-action="Index" asp-route-id="@(prevPage)"> &lt Previous </a>
              }

              <span class="current-page">Page @ViewBag.Page</span>
              
              @if (ViewBag.Page <= ViewBag.DealCount/ViewBag.Size)
              {
                <a asp-action="Index" asp-route-id="@(nextPage)">Next &gt </a>
              }
            </div>
          </div>
        </div>
      </div>
    </div>



    <div class='deals-cards-container'>
      @foreach (var pinnedDeal in Model)
      {
        <div class="ui cards">
          <div class="card">
            <div class="ui top">
              <a><i class="thumbtack icon large red"></i></a>
            </div>
            <div class="content">
              <div class="header">
                @pinnedDeal.Deal.Item.ItemName
                <h4>
                  @pinnedDeal.Deal.Price
                </h4>
                </div>
              <div class="description">
                <div>
                  @pinnedDeal.Deal.Location.Name
                </div>
                <div>
                  @pinnedDeal.Deal.Location.Address
                </div>
                <div>
                  @pinnedDeal.Deal.TimeUpdated
                  @* @pinnedDeal.Deal.TimeUpdated.Day/@pinnedDeal.Deal.TimeUpdated.Month/@pinnedDeal.Deal.TimeUpdated.Year @pinnedDeal.Deal.TimeUpdated.Hour:@pinnedDeal.Deal.TimeUpdated.Minute *@
                </div>
                <div>
                  @* @APIUser.Get(@pinnedDeal.Deal.UserId) *@
                </div>
              </div>
            </div>
            <div class="ui bottom">
              <a><i class="thumbs up outline icon blue large"></i></a>
              <a><i class="thumbs down outline icon red large"></i></a>
            </div>
          </div>
        </div>
      }
    </div>

  </div>


} @* End of ELSE statement *@
</div>

WisePriceClient/Views/Deals/Posted.cshtml
@{
    ViewData["Title"] = "Posted Deals";
}

@{
  int nextPage = ViewBag.Page + 1;
  int prevPage = ViewBag.Page - 1;
}

@using WisePriceClient.Models
@model List<PostedDeal>

<div class="exceptionError">
@if (TempData.ContainsKey("ErrorMessage"))
{
  <div class='deals-body'>
    <div class='deals-top'>
      <div class='col'></div>
      <h1>My Posted Deals</h1>
      <div class='col'>
      </div>
    </div>
    <h4>@TempData["ErrorMessage"]</h4>
  </div>
}
else
{

  <div class='deals-body'>
    <div class='deals-top'>
      <div class='col'></div>
      <h1>Posted Deals</h1>
      <div class='col'>
        <div class='pagination'>
          <div>
            @((ViewBag.Page - 1) * (ViewBag.Size) + 1) - @((ViewBag.Page - 1) * (ViewBag.Size) + Model.Count) of @ViewBag.DealCount results
          </div>
          <div>
            <div class='page-nav'>
              @if (ViewBag.Page > 1)
              {
                <a  asp-action="Index" asp-route-id="@(prevPage)"> &lt Previous </a>
              }

              <span class="current-page">Page @ViewBag.Page</span>
              
              @if (ViewBag.Page <= ViewBag.DealCount/ViewBag.Size)
              {
                <a asp-action="Index" asp-route-id="@(nextPage)">Next &gt </a>
              }
            </div>
          </div>
        </div>
      </div>
    </div>

    <h3>Posted by: @User.Identity.Name</h3>


    <div class='deals-cards-container'>
      @foreach (var deal in Model)
      {
        <div class="ui cards">
          <div class="card">
            <div class="ui top">
              <a><i class="thumbtack icon large"></i></a>
            </div>
            <div class="content">
              <div class="header">
                @deal.Deal.Item.ItemName
                <h4>
                  @deal.Deal.Price
                </h4>
              </div>
              <div class="description">
                <div>
                  @deal.Deal.Location.Name
                </div>
                <div>
                  @deal.Deal.Location.Address
                </div>
                <div>
                  @deal.Deal.TimeUpdated
                </div>
              </div>
            </div>
              <div class="ui bottom">
                <a class='ui button grey' asp-route-id='@deal.DealId' asp-action='Edit'>Edit</a>
                <form asp-controller="Deals" asp-action="Delete" method="post">
                  <input type='hidden' value='@deal.DealId' name='DealId'>
                  <input type="submit" value="Delete" class="ui button"/>
                </form>
              </div>
          </div>
        </div>
      }
    </div>

  </div>
}@* End of ELSE statement *@
</div>